### ISSUE TITLE
Check to ensure display-internal and listen.js utilize Meta.time ticker

### ISSUE THREAD

**Issue by Lovinity** [Lovinity/wwsu#10]
Display internal is not correctly loading announcement slides. I suspect it's because I forgot to implement the Meta.time ticker (since the web sockets no longer pushes Meta.time every second). Also check the Listener's Corner page to ensure it too is utilizing a Meta.time ticker. If not, fix this.

- [x] Check for use of Meta.time ticker in display-internal and listen.js.

- [x] If a ticker is not being used, implement it.

- [x] Monitor and test fix on display internal.

**Comment by Lovinity** [comment]
FAILED on commit 2fa4d53
